site_name: ML - DL Algorithms From Scratch
theme:
  logo: assets/deep-learning.png
  favicon: assets/deep-learning.png
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: black


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/necmettin-ceylan/

    - icon: fontawesome/brands/github
      link: https://github.com/NecmettinCeylan

    - icon: fontawesome/brands/medium
      link: https://medium.com/@necocyln




copyright: Copyright &copy; 2023-2024 Necmettin Ceylan