site_name: ML - DL Algorithms From Scratch
theme:
  logo: assets/deep-learning.png
  favicon: assets/deep-learning.png
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: black
  
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/necmettin-ceylan/

    - icon: fontawesome/brands/github
      link: https://github.com/NecmettinCeylan

    - icon: fontawesome/brands/medium
      link: https://medium.com/@necocyln


copyright: Copyright &copy; 2023-2024 Necmettin Ceylan