site_name: ML - DL Algorithms From Scratch
theme:
  logo: assets/deep-learning.png
  favicon: assets/deep-learning.png
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: black
  


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css